[gspread]
type = "service_account"
project_id = "study-459605"
private_key_id = "fa1566f96b8133fb4fa7efb1604471e85d85e333"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCwpLHowB9yjCkc
kM9pE0bI4aqrbml4sQ4UpiyNzJ1AF6pSSMVObKlU1RuBeDzLerClFWscLFm04xiS
MIhL5O62pDOUj6RgPBSV2o/q9nWPC2Na+k7eHz2dcat46S3dceozMyl/xhojfg80
HPaBRZA5EgC+fdg+aQ2MH0XSxudrZWp+N+hxZQutcAyEwmNeiSQULfFToAQ/Gl4W
GWbsP0UbxvGz+yo1kGBn6Awc4O7phq57zbXnUTw6ROXbekj46nQsXCmFEy6dZBg9
cvnq2qKamT2pj/fQuPP/StmsLtg3MNzvNiMYVu501MTPV6XZwkM0rE08cr6um1FJ
HPFNR0npAgMBAAECggEAAj1G73NGvXOEbpMcELIeCBxARyXCWuAtFFrvnqk/kcPw
X1RX2ADYUWCAQERvdN7serNKT9RKG4PI2HWat2eYFSMAxRCLHhiKOZod5Uspk14q
wh5Wk0n5xH4KlUuozrFhLYlSVzHXkVKe9mNVnARElKH4oMbvT7SSPOVamRZMxxeV
IkbSf0cO5WDukpCqCLk6f+m1O2cIFumcaYzUkmbiMLEN3NXtOVIMM1/YORETZG5w
CyEL2MniXnu7EYuc09ce6EhejL4QfRTHAmu9S0K9y22GsJepz/RPKFFPjXNkUxsl
TL7W0u3iuPagkIJC8NgD7oDG24eDvYxb0F9R2leCWQKBgQDovY9dXRe4cWwu+FlX
7NAWcsuk1ABABzSTKE42ZiC2BflbatZksverokSK57WwmxTfbR2h/mfkV3psMaXt
ZdSQwSlzGIkcpTK30kvUienDUaEpl3UHt8tMujNGkOND/SyH3sQuHRv9Wns2gcWp
tgbs/ZKCVk8QLeccIdSdnSGfPQKBgQDCS/Gwlp8hSVFFYybEdMZJAOPSCVNnzFoP
l0pA1ZPtCjl3GK3RMa55RtTgmXldlC812P7CdjfQqPyh1wRCRYFmF94vH3kagDL9
9o3Jti2BGdR0K0M6k2vzLvfguYjCcifzHT2oOiAw4T0zKLNHIqq3RMymf1EL/8ZT
o1AQNd1AHQKBgF2ocrnqjXIeyp84N5Pna3GtLoAdBCDABYs2jAreHEnDq637F12c
m4hJG3YeeoIgVkz29xbKbvp3rX8+l3wqH1lFMi3r8LlDTV6l1Pgpq5V7EvTOyzyY
3Mn6oEnEYoBosHPY1G+OLUZOFAlCPc3mv3C9NikXHGfxYPB0OMBYjEAtAoGAawo9
v4RrbIIg1PI35FlU99kWqZrbqT6KizZVAPzo/tj4KaWd9LbDISslkgrbMvO1Qpwm
Vemc/EZsz5hOT1hNXnpdvGZBaJkh/om7OVo1HX+mbM18vyOCgDnq85IjRsRvP99n
HWvQWj1sYufURKdTl52+hSd09gBWObOqIxQZrP0CgYEApKxcYuJxOA7ab6UhrkTE
gqehc1UJZ64efSh653HNO/IOicnLzusTm91kZcboTF4+6i2UrnzOm215gnMyEzOX
4zwDTvzycRU3j8HCZj+y6vgh7+/BYJMYLzgIYQ9pSYdlPF+RLpjQjvwWO8I89PR0
RJ2R+cUdRsAlQlHOBCDjqZo=
-----END PRIVATE KEY-----"""
client_email = "sheet-bot@study-459605.iam.gserviceaccount.com"
client_id = "109542141143546261414"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/sheet-bot%40study-459605.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
